import sys
sys.path.insert(0, r'F:\Odoo_Devs\odoo19')
import odoo
from odoo.api import Environment

odoo.tools.config.parse_config(['-c', 'odoo.conf'])
from odoo.modules.registry import Registry
registry = Registry('Odoo19')
with registry.cursor() as cr:
    env = Environment(cr, odoo.SUPERUSER_ID, {})
    user_7 = env['res.users'].browse(7)
    
    # Let's inspect the exact domain evaluation for User 7
    print("User 7 Employee Name:", user_7.employee_id.name if user_7.employee_id else "NONE")
    print("User 7 Employee Operating Unit ID:", user_7.employee_id.default_operating_unit_id.id if user_7.employee_id else "NONE")
    
    # Evaluate domain for user 7 specifically
    Model = env['planning.work.unit.manpower'].with_user(user_7)
    domain_7 = env['ir.rule'].with_user(user_7)._compute_domain('planning.work.unit.manpower', 'read')
    print("Computed domain for User 7:", domain_7)
    
    # Query database using SQL generated by search
    query = Model._search(domain_7)
    sql, params = query.select()
    print("SQL query generated:")
    print(sql)
    print("SQL params:", params)
    
    # Run the query
    cr.execute(sql, params)
    results = cr.fetchall()
    print("Query results (IDs):", [r[0] for r in results])
