[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$B0DIGUPI2bt3bs05R8jZew$.R4HJ7odr1THXvJLxpHNGxOSFfbuLBavT5A11SSY3UVOdyDdXZQ7.mDEvW3r2xDMKlI5QBNkyj8xiAY5GRHltQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

