# -*- coding: utf-8 -*-

from . import applicant_assessment
from . import applicant_shortlist
from . import assessment_criteria
from . import blacklist_pool
from . import candidate_shortlist
from . import internal_job_position
from . import internal_recruitment
from . import interview_assessment
from . import job_vacancy_competency
from . import job_vacancy
from . import recruitment_process_external
from . import recruitment_process_internal
from . import selected_external
from . import selected_internal
from . import employee_probation
from . import employee_transfer
from . import transfer_ranking
from . import recruitment_request
from . import recruitment_scoring
from . import hr_applicant
from . import employee_education
from . import talent_roster
from . import recruitment_master_data
from . import external_shortlist_default_criteria
from . import res_config_settings
from . import acting_role
from . import hr_attendance
from . import hr_job
from . import recruitment_application_window
from . import recruitment_available_vacancy
from . import recruitment_competency
from . import recruitment_experience
from . import recruitment_experience_weight_config
from . import recruitment_master_data_probation
from . import recruitment_offer_letter
from . import recruitment_penalty_deduction
from . import recruitment_qualifications
from . import transfer_assessment