from . import cbs_service
from . import helpdesk_ticket_escalation
from . import helpdesk_ticket_case_type
from . import helpdesk_ticket_customer_type
from . import helpdesk_ticket
from . import helpdesk_ticket_stage
from . import helpdesk_ticket_tag
from . import helpdesk_ticket_channel
from . import helpdesk_ticket_category
from . import helpdesk_ticket_team
from . import helpdesk_sla
from . import helpdesk_ticket_timesheet
from . import account_analytic_line
from . import ir_http
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import helpdesk_service_catalogue
from . import helpdesk_ola
from . import helpdesk_knowledge
from . import helpdesk_social_channel
from . import helpdesk_team_operation
